channels:
- conda-forge
dependencies:
- astropy=6.0.1
- bilby=2.2.2
- corner=2.2.2
- dynesty=2.1.2
- gwosc=0.7.1
- gwpy=3.0.8
- h5py=3.10.0
- jupyter=1.0.0
- jupyter_client=8.2.0
- jupyter_console=6.6.3
- jupyter_core=5.3.0
- lalsuite=7.21
- ligo.skymap=1.0.3
- matplotlib=3.7.3
- notebook=6.5.4
- numpy=1.23.5
- pandas=2.0.1
- pip=23.1.1
- pycbc=2.0.5
- pygcn=1.0.2
- python=3.9.16
- scipy=1.8.1
- wget=1.20.3
- pesummary=1.2.0
- gwpopulation=0.10.0
name: igwn-py39-lw
